input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => {
      "message" => [
        "^%{TIMESTAMP_ISO8601:[app][timestamp]}\s+%{LOGLEVEL:[log][level]}\s+%{NUMBER:[process][pid]:int}\s+---\s+\[%{DATA:[spring][application][name]}\]\s+\[%{DATA:[process][thread][name]}\]\s+%{DATA:[log][logger]}\s+:\s+%{GREEDYDATA:[log][message]}$",
        "^%{TIMESTAMP_ISO8601:[app][timestamp]}\s+%{LOGLEVEL:[log][level]}\s+%{NUMBER:[process][pid]:int}\s+---\s+\[%{DATA:[process][thread][name]}\]\s+%{DATA:[log][logger]}\s+:\s+%{GREEDYDATA:[log][message]}$"
      ]
    }
  }

  date {
    match => [ "[app][timestamp]", "ISO8601" ]
    target => "@timestamp"
  }

  mutate {
    add_field => {
      "[service][name]" => "warehouse-backend"
      "[event][dataset]" => "warehouse.backend"
      "[observer][type]" => "logstash"
    }
    remove_field => [ "[app][timestamp]", "app_service" ]
  }

  if [log][level] and [log][level] != "" {
    mutate {
      uppercase => [ "[log][level]" ]
    }
  }

  if "_grokparsefailure" in [tags] {
    mutate {
      add_tag => [ "unparsed_log_line" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "warehouse-backend-logs-v2-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
